# ADD API Client below

ctp.projectKey=training-exjs-20260115-shared
ctp.clientId=Fm5l9g5n5_ESjnJYhU6pM6Cl
ctp.clientSecret=9eC5c5-ZV6O2b-D_zV8LrtAFQu21qEb1
ctp.authUrl=https://auth.europe-west1.gcp.commercetools.com
ctp.apiUrl=https://api.europe-west1.gcp.commercetools.com
ctp.scopes=manage_project:training-exjs-20260115-shared

spring.devtools.restart.enabled=true
spring.jackson.default-property-inclusion=non_null
server.error.whitelabel.enabled=false
server.port=8080

